(defun color-theme-luolE-blood-and-sand ()
  "Color subtheme, created 2010-07-29."
  (interactive)
  (color-theme-install
   '(color-theme-luolE-blood-and-sand nil nil
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yas/field-debug-face ((t (nil))))
     (widget-single-line-field ((t (:background "gray30" :foreground "orange"))))
     (widget-mouse-face ((t (:bold t :background "brown4" :foreground "white" :weight bold))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-field ((t (:background "gray30" :foreground "orange"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-button ((t (:bold t :weight bold))))
     (vertical-border ((t (nil))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (underline ((t (:underline t))))
     (trailing-whitespace ((t (:background "red1"))))
     (tooltip ((t (:background "systeminfowindow" :foreground "systeminfotext" :family "Sans Serif"))))
     (tool-tips ((t (:background "lightyellow" :foreground "black" :family "Sans Serif"))))
     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
     (tabbar-unselected-face ((t (:background "gray30" :foreground "gray70" :box (:line-width 2 :color "gray30") :height 0.8 :family "Cambria"))))
     (tabbar-separator-face ((t (:background "gray30" :foreground "gray70" :height 0.16000000000000003 :family "Cambria"))))
     (tabbar-selected-face ((t (:bold t :background "#A6E22A" :foreground "black" :box (:line-width 1 :color "#B0FF2A") :weight bold :height 100 :family "Cambria"))))
     (tabbar-default-face ((t (:background "gray30" :foreground "gray70" :height 0.8 :family "Cambria"))))
     (tabbar-button-face ((t (:background "gray30" :foreground "dark red" :box (:line-width 1 :color "gray30") :height 0.8 :family "Cambria"))))
     (speedbar-tag-face ((t (:foreground "#f57900"))))
     (speedbar-separator-face ((t (:background "firebrick" :foreground "tan1"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-highlight-face ((t (:background "gray30"))))
     (speedbar-file-face ((t (:foreground "burlywood1"))))
     (speedbar-directory-face ((t (:foreground "NavajoWhite1"))))
     (speedbar-button-face ((t (:foreground "tan1"))))
     (show-paren-mismatch ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (show-paren-match ((t (:background "#73d216" :foreground "#2e3436"))))
     (shadow ((t (:foreground "grey70"))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (scroll-bar ((t (:foreground "systemscrollbar"))))
     (region ((t (:background "brown4" :foreground "tan1"))))
     (query-replace ((t (:background "#f57900" :foreground "#2e3436"))))
     (pulldown-default-selection-face ((t (:background "steelblue" :foreground "white"))))
     (pulldown-default-face ((t (:background "lightgray" :foreground "black" :underline "darkgray"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (org-verse ((t (:italic t :foreground "#bbbbbc" :slant italic))))
     (org-verbatim ((t (:italic t :foreground "#eeeeec" :underline t :slant italic))))
     (org-todo ((t (:bold t :foreground "Red" :weight bold))))
     (org-special-keyword ((t (:foreground "brown"))))
     (org-quote ((t (:italic t :foreground "#bbbbbc" :slant italic))))
     (org-link ((t (:background "#2e3436" :foreground "skyblue2"))))
     (org-level-4 ((t (:bold t :foreground "tomato" :weight bold :height 1.0))))
     (org-level-3 ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
     (org-level-2 ((t (:bold t :foreground "#6ac214" :weight bold :height 1.2))))
     (org-level-1 ((t (:bold t :foreground "dodger blue" :weight bold :height 1.5))))
     (org-hide ((t (:foreground "#2e3436"))))
     (org-footnote ((t (:foreground "magenta3" :underline t))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-date ((t (:foreground "magenta3" :underline t))))
     (org-block ((t (:foreground "#bbbbbc"))))
     (one-key-title ((t (:foreground "Gold"))))
     (one-key-prompt ((t (:foreground "khaki3"))))
     (one-key-keystroke ((t (:foreground "DarkRed"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (next-error ((t (:background "dark slate blue" :foreground "black"))))
     (mouse ((t (:background "#8ae234"))))
     (mode-line-inactive ((t (:background "#555753" :foreground "#bbbbbc" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-buffer-id ((t (:bold t :foreground "orange" :weight bold))))
     (mode-line ((t (:background "black" :foreground "gray15" :box (:line-width 1 :color nil :style released-button)))))
     (minibuffer-prompt ((t (:bold t :foreground "#729fcf" :weight bold))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-header-xheader-face ((t (:foreground "DeepSkyBlue1"))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-header-to ((t (:foreground "white"))))
     (message-header-subject ((t (:foreground "white"))))
     (message-header-other-face ((t (:foreground "VioletRed1"))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-name-face ((t (:foreground "green"))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-cc ((t (:foreground "white"))))
     (message-cited-text ((t (:foreground "#edd400"))))
     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
     (match ((t (:bold t :background "#e9b96e" :foreground "#2e3436" :weight bold))))
     (linum ((t (:background "#1A1A1A" :foreground "#505050"))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (link ((t (:foreground "dodger blue" :underline t))))
     (lazy-highlight ((t (:background "#e9b96e" :foreground "#2e3436"))))
     (italic ((t (:italic t :underline nil :slant italic))))
     (isearch-fail ((t (:background "red4"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     (info-xref ((t (:foreground "#729fcf"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-incomplete-regexp ((t (:bold t :foreground "#f57900" :weight bold))))
     (ido-first-match ((t (:bold t :weight bold))))
     (hl-paren-face ((t (:bold t :weight bold :width expanded))))
     (hl-line ((t (:background "brown4"))))
     (highlight-tail-face-default-9 ((t (:background "#A92121"))))
     (highlight-tail-face-default-80 ((t (:background "#020000"))))
     (highlight-tail-face-default-8 ((t (:background "#AC2222"))))
     (highlight-tail-face-default-79 ((t (:background "#050101"))))
     (highlight-tail-face-default-78 ((t (:background "#070101"))))
     (highlight-tail-face-default-77 ((t (:background "#090202"))))
     (highlight-tail-face-default-76 ((t (:background "#0C0202"))))
     (highlight-tail-face-default-75 ((t (:background "#0E0303"))))
     (highlight-tail-face-default-74 ((t (:background "#100303"))))
     (highlight-tail-face-default-73 ((t (:background "#130404"))))
     (highlight-tail-face-default-72 ((t (:background "#150404"))))
     (highlight-tail-face-default-71 ((t (:background "#180505"))))
     (highlight-tail-face-default-70 ((t (:background "#1A0505"))))
     (highlight-tail-face-default-7 ((t (:background "#AE2222"))))
     (highlight-tail-face-default-69 ((t (:background "#1C0606"))))
     (highlight-tail-face-default-68 ((t (:background "#1F0606"))))
     (highlight-tail-face-default-67 ((t (:background "#210606"))))
     (highlight-tail-face-default-66 ((t (:background "#230707"))))
     (highlight-tail-face-default-65 ((t (:background "#260707"))))
     (highlight-tail-face-default-64 ((t (:background "#280808"))))
     (highlight-tail-face-default-63 ((t (:background "#2A0808"))))
     (highlight-tail-face-default-62 ((t (:background "#2D0909"))))
     (highlight-tail-face-default-61 ((t (:background "#2F0909"))))
     (highlight-tail-face-default-60 ((t (:background "#310A0A"))))
     (highlight-tail-face-default-6 ((t (:background "#B02323"))))
     (highlight-tail-face-default-59 ((t (:background "#340A0A"))))
     (highlight-tail-face-default-58 ((t (:background "#360B0B"))))
     (highlight-tail-face-default-57 ((t (:background "#380B0B"))))
     (highlight-tail-face-default-56 ((t (:background "#3B0C0C"))))
     (highlight-tail-face-default-55 ((t (:background "#3D0C0C"))))
     (highlight-tail-face-default-54 ((t (:background "#3F0C0C"))))
     (highlight-tail-face-default-53 ((t (:background "#420D0D"))))
     (highlight-tail-face-default-52 ((t (:background "#440D0D"))))
     (highlight-tail-face-default-51 ((t (:background "#470E0E"))))
     (highlight-tail-face-default-50 ((t (:background "#490E0E"))))
     (highlight-tail-face-default-5 ((t (:background "#B32323"))))
     (highlight-tail-face-default-49 ((t (:background "#4B0F0F"))))
     (highlight-tail-face-default-48 ((t (:background "#4E0F0F"))))
     (highlight-tail-face-default-47 ((t (:background "#501010"))))
     (highlight-tail-face-default-46 ((t (:background "#521010"))))
     (highlight-tail-face-default-45 ((t (:background "#551111"))))
     (highlight-tail-face-default-44 ((t (:background "#571111"))))
     (highlight-tail-face-default-43 ((t (:background "#591212"))))
     (highlight-tail-face-default-42 ((t (:background "#5C1212"))))
     (highlight-tail-face-default-41 ((t (:background "#5E1313"))))
     (highlight-tail-face-default-40 ((t (:background "#601313"))))
     (highlight-tail-face-default-4 ((t (:background "#B52424"))))
     (highlight-tail-face-default-39 ((t (:background "#631313"))))
     (highlight-tail-face-default-38 ((t (:background "#651414"))))
     (highlight-tail-face-default-37 ((t (:background "#671414"))))
     (highlight-tail-face-default-36 ((t (:background "#6A1515"))))
     (highlight-tail-face-default-35 ((t (:background "#6C1515"))))
     (highlight-tail-face-default-34 ((t (:background "#6E1616"))))
     (highlight-tail-face-default-33 ((t (:background "#711616"))))
     (highlight-tail-face-default-32 ((t (:background "#731717"))))
     (highlight-tail-face-default-31 ((t (:background "#751717"))))
     (highlight-tail-face-default-30 ((t (:background "#781818"))))
     (highlight-tail-face-default-3 ((t (:background "#B72424"))))
     (highlight-tail-face-default-29 ((t (:background "#7A1818"))))
     (highlight-tail-face-default-28 ((t (:background "#7D1919"))))
     (highlight-tail-face-default-27 ((t (:background "#7F1919"))))
     (highlight-tail-face-default-26 ((t (:background "#811919"))))
     (highlight-tail-face-default-25 ((t (:background "#841A1A"))))
     (highlight-tail-face-default-24 ((t (:background "#861A1A"))))
     (highlight-tail-face-default-23 ((t (:background "#881B1B"))))
     (highlight-tail-face-default-22 ((t (:background "#8B1B1B"))))
     (highlight-tail-face-default-21 ((t (:background "#8D1C1C"))))
     (highlight-tail-face-default-20 ((t (:background "#8F1C1C"))))
     (highlight-tail-face-default-2 ((t (:background "#BA2525"))))
     (highlight-tail-face-default-19 ((t (:background "#921D1D"))))
     (highlight-tail-face-default-18 ((t (:background "#941D1D"))))
     (highlight-tail-face-default-17 ((t (:background "#961E1E"))))
     (highlight-tail-face-default-16 ((t (:background "#991E1E"))))
     (highlight-tail-face-default-15 ((t (:background "#9B1F1F"))))
     (highlight-tail-face-default-14 ((t (:background "#9D1F1F"))))
     (highlight-tail-face-default-13 ((t (:background "#A01F1F"))))
     (highlight-tail-face-default-12 ((t (:background "#A22020"))))
     (highlight-tail-face-default-11 ((t (:background "#A42020"))))
     (highlight-tail-face-default-10 ((t (:background "#A72121"))))
     (highlight-tail-face-default-1 ((t (:background "#BC2525"))))
     (highlight-tail-face-\#4D4D4D-9 ((t (:background "#B12929"))))
     (highlight-tail-face-\#4D4D4D-80 ((t (:background "#4E4D4D"))))
     (highlight-tail-face-\#4D4D4D-8 ((t (:background "#B22929"))))
     (highlight-tail-face-\#4D4D4D-79 ((t (:background "#504C4C"))))
     (highlight-tail-face-\#4D4D4D-78 ((t (:background "#514C4C"))))
     (highlight-tail-face-\#4D4D4D-77 ((t (:background "#534B4B"))))
     (highlight-tail-face-\#4D4D4D-76 ((t (:background "#544B4B"))))
     (highlight-tail-face-\#4D4D4D-75 ((t (:background "#554A4A"))))
     (highlight-tail-face-\#4D4D4D-74 ((t (:background "#574A4A"))))
     (highlight-tail-face-\#4D4D4D-73 ((t (:background "#584949"))))
     (highlight-tail-face-\#4D4D4D-72 ((t (:background "#594949"))))
     (highlight-tail-face-\#4D4D4D-71 ((t (:background "#5B4848"))))
     (highlight-tail-face-\#4D4D4D-70 ((t (:background "#5C4848"))))
     (highlight-tail-face-\#4D4D4D-7 ((t (:background "#B42828"))))
     (highlight-tail-face-\#4D4D4D-69 ((t (:background "#5E4747"))))
     (highlight-tail-face-\#4D4D4D-68 ((t (:background "#5F4747"))))
     (highlight-tail-face-\#4D4D4D-67 ((t (:background "#604646"))))
     (highlight-tail-face-\#4D4D4D-66 ((t (:background "#624646"))))
     (highlight-tail-face-\#4D4D4D-65 ((t (:background "#634545"))))
     (highlight-tail-face-\#4D4D4D-64 ((t (:background "#654545"))))
     (highlight-tail-face-\#4D4D4D-63 ((t (:background "#664444"))))
     (highlight-tail-face-\#4D4D4D-62 ((t (:background "#674444"))))
     (highlight-tail-face-\#4D4D4D-61 ((t (:background "#694343"))))
     (highlight-tail-face-\#4D4D4D-60 ((t (:background "#6A4343"))))
     (highlight-tail-face-\#4D4D4D-6 ((t (:background "#B52828"))))
     (highlight-tail-face-\#4D4D4D-59 ((t (:background "#6C4242"))))
     (highlight-tail-face-\#4D4D4D-58 ((t (:background "#6D4242"))))
     (highlight-tail-face-\#4D4D4D-57 ((t (:background "#6E4141"))))
     (highlight-tail-face-\#4D4D4D-56 ((t (:background "#704141"))))
     (highlight-tail-face-\#4D4D4D-55 ((t (:background "#714040"))))
     (highlight-tail-face-\#4D4D4D-54 ((t (:background "#724040"))))
     (highlight-tail-face-\#4D4D4D-53 ((t (:background "#743F3F"))))
     (highlight-tail-face-\#4D4D4D-52 ((t (:background "#753F3F"))))
     (highlight-tail-face-\#4D4D4D-51 ((t (:background "#773E3E"))))
     (highlight-tail-face-\#4D4D4D-50 ((t (:background "#783E3E"))))
     (highlight-tail-face-\#4D4D4D-5 ((t (:background "#B62727"))))
     (highlight-tail-face-\#4D4D4D-49 ((t (:background "#793D3D"))))
     (highlight-tail-face-\#4D4D4D-48 ((t (:background "#7B3D3D"))))
     (highlight-tail-face-\#4D4D4D-47 ((t (:background "#7C3C3C"))))
     (highlight-tail-face-\#4D4D4D-46 ((t (:background "#7E3C3C"))))
     (highlight-tail-face-\#4D4D4D-45 ((t (:background "#7F3B3B"))))
     (highlight-tail-face-\#4D4D4D-44 ((t (:background "#803B3B"))))
     (highlight-tail-face-\#4D4D4D-43 ((t (:background "#823A3A"))))
     (highlight-tail-face-\#4D4D4D-42 ((t (:background "#833A3A"))))
     (highlight-tail-face-\#4D4D4D-41 ((t (:background "#853939"))))
     (highlight-tail-face-\#4D4D4D-40 ((t (:background "#863939"))))
     (highlight-tail-face-\#4D4D4D-4 ((t (:background "#B82727"))))
     (highlight-tail-face-\#4D4D4D-39 ((t (:background "#873838"))))
     (highlight-tail-face-\#4D4D4D-38 ((t (:background "#893838"))))
     (highlight-tail-face-\#4D4D4D-37 ((t (:background "#8A3737"))))
     (highlight-tail-face-\#4D4D4D-36 ((t (:background "#8B3737"))))
     (highlight-tail-face-\#4D4D4D-35 ((t (:background "#8D3636"))))
     (highlight-tail-face-\#4D4D4D-34 ((t (:background "#8E3636"))))
     (highlight-tail-face-\#4D4D4D-33 ((t (:background "#903535"))))
     (highlight-tail-face-\#4D4D4D-32 ((t (:background "#913535"))))
     (highlight-tail-face-\#4D4D4D-31 ((t (:background "#923434"))))
     (highlight-tail-face-\#4D4D4D-30 ((t (:background "#943434"))))
     (highlight-tail-face-\#4D4D4D-3 ((t (:background "#B92626"))))
     (highlight-tail-face-\#4D4D4D-29 ((t (:background "#953333"))))
     (highlight-tail-face-\#4D4D4D-28 ((t (:background "#973333"))))
     (highlight-tail-face-\#4D4D4D-27 ((t (:background "#983232"))))
     (highlight-tail-face-\#4D4D4D-26 ((t (:background "#993232"))))
     (highlight-tail-face-\#4D4D4D-25 ((t (:background "#9B3131"))))
     (highlight-tail-face-\#4D4D4D-24 ((t (:background "#9C3131"))))
     (highlight-tail-face-\#4D4D4D-23 ((t (:background "#9D3030"))))
     (highlight-tail-face-\#4D4D4D-22 ((t (:background "#9F3030"))))
     (highlight-tail-face-\#4D4D4D-21 ((t (:background "#A02F2F"))))
     (highlight-tail-face-\#4D4D4D-20 ((t (:background "#A22F2F"))))
     (highlight-tail-face-\#4D4D4D-2 ((t (:background "#BB2626"))))
     (highlight-tail-face-\#4D4D4D-19 ((t (:background "#A32E2E"))))
     (highlight-tail-face-\#4D4D4D-18 ((t (:background "#A42E2E"))))
     (highlight-tail-face-\#4D4D4D-17 ((t (:background "#A62D2D"))))
     (highlight-tail-face-\#4D4D4D-16 ((t (:background "#A72D2D"))))
     (highlight-tail-face-\#4D4D4D-15 ((t (:background "#A92C2C"))))
     (highlight-tail-face-\#4D4D4D-14 ((t (:background "#AA2C2C"))))
     (highlight-tail-face-\#4D4D4D-13 ((t (:background "#AB2B2B"))))
     (highlight-tail-face-\#4D4D4D-12 ((t (:background "#AD2B2B"))))
     (highlight-tail-face-\#4D4D4D-11 ((t (:background "#AE2A2A"))))
     (highlight-tail-face-\#4D4D4D-10 ((t (:background "#B02A2A"))))
     (highlight-tail-face-\#4D4D4D-1 ((t (:background "#BC2525"))))
     (highlight-symbol-face ((t (:background "gray30"))))
     (highlight ((t (:background "brown4"))))
     (hi-yellow ((t (:background "yellow1" :foreground "black"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-pink ((t (:background "pink" :foreground "black"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-green ((t (:background "green1" :foreground "black"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-blue ((t (:background "light blue" :foreground "black"))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "Sans Serif"))))
     (hi-black-b ((t (:bold t :weight bold))))
     (help-argument-name ((t (nil))))
     (header-line ((t (:box (:line-width 1 :color nil :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (gnus-summary-selected ((t (:background "brown4" :foreground "white"))))
     (gnus-summary-normal-unread-face ((t (:foreground "white"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "indian red"))))
     (gnus-summary-normal-read-face ((t (:foreground "lime green"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "royal blue"))))
     (gnus-summary-low-unread-face ((t (:italic t :foreground "white" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "dark red" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "royal blue" :slant italic))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "lime green" :slant italic))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "white" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "tomato" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "lime green" :weight bold))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "rotal blue" :weight bold))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-signature-face ((t (:italic t :foreground "dark grey" :slant italic))))
     (gnus-header-subject ((t (:foreground "#edd400"))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3" :slant italic :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "#729fcf" :weight bold))))
     (gnus-header-from ((t (:bold t :foreground "#edd400" :weight bold))))
     (gnus-header-content ((t (:italic t :foreground "#8ae234" :slant italic))))
     (gnus-group-news-low-face ((t (:bold t :foreground "dodger blue" :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "#edd400" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "#729fcf"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "dodger blue" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "#edd400" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "#729fcf"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-mail-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-cite-face-4 ((t (:foreground "PaleTurquoise4"))))
     (gnus-cite-face-3 ((t (:foreground "khaki4"))))
     (gnus-cite-face-2 ((t (:foreground "sienna4"))))
     (gnus-cite-face-1 ((t (:foreground "#ad7fa8"))))
     (fs-line-face ((t (:foreground "green" :underline nil :weight normal))))
     (fs-file-name-mouse-face ((t (:background "yellow"))))
     (fs-file-name-face ((t (:bold t :foreground "red" :underline t :weight bold))))
     (fringe ((t (:background "grey10"))))
     (font-lock-warning-face ((t (:bold t :foreground "#f57900" :weight bold))))
     (font-lock-variable-name-face ((t (:foreground "tomato"))))
     (font-lock-type-face ((t (:bold t :foreground "firebrick" :weight bold))))
     (font-lock-string-face ((t (:italic t :foreground "NavajoWhite4" :overline t :underline t :slant italic))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold :underline nil :underline nil :weight))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :underline nil :underline nil :weight))))
     (font-lock-preprocessor-face ((t (:foreground "#729fcf"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-keyword-face ((t (:bold t :foreground "tan2" :weight bold))))
     (font-lock-function-name-face ((t (:bold t :foreground "firebrick2" :weight bold))))
     (font-lock-doc-face ((t (:italic t :foreground "#888a85" :overline t :underline t :slant italic))))
     (font-lock-constant-face ((t (:foreground "salmon1"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#888a85"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (expander-face ((t (:background "darkblue" :foreground "white"))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "White" :weight bold))))
     (eshell-ls-special-face ((t (:bold t :foreground "Gold" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "black" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "Coral" :weight bold))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "DimGray" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (epa-validity-medium ((t (:italic t :foreground "PaleTurquoise" :slant italic))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-string ((t (:foreground "lightyellow"))))
     (epa-mark ((t (:bold t :foreground "orange" :weight bold))))
     (epa-field-name ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-field-body ((t (:italic t :foreground "turquoise" :slant italic))))
     (dropdown-list-selection-face ((t (:background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "DejaVu Sans Mono"))))
     (dropdown-list-face ((t (:background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "DejaVu Sans Mono"))))
     (dired-warning ((t (:bold t :foreground "#f57900" :weight bold))))
     (dired-symlink ((t (:bold t :foreground "tan2" :weight bold))))
     (dired-perm-write ((t (:background "black" :foreground "NavajoWhite" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "DejaVu Sans Mono"))))
     (dired-marked ((t (:bold t :foreground "#f57900" :weight bold))))
     (dired-mark ((t (:foreground "salmon1"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-header ((t (:bold t :foreground "firebrick" :weight bold))))
     (dired-flagged ((t (:bold t :foreground "#f57900" :weight bold))))
     (dired-directory ((t (:bold t :foreground "firebrick2" :weight bold))))
     (diary-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (custom-visibility ((t (:foreground "dodger blue" :underline t :height 0.8))))
     (custom-variable-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
     (custom-variable-button ((t (:background "grey50" :foreground "black" :box (:line-width 1 :style released-button)))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-state-face ((t (:foreground "lime green"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-saved ((t (:underline t))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-link ((t (:foreground "dodger blue" :underline t))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-group-tag-1 ((t (:bold t :foreground "pink" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-group-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.3))))
     (custom-face-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
     (custom-documentation ((t (:italic t :slant italic))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-button-unraised ((t (:background "grey50" :foreground "black"))))
     (custom-button-pressed-unraised ((t (:background "grey50" :foreground "violet"))))
     (custom-button-pressed ((t (:background "grey50" :foreground "black" :box (:style pressed-button)))))
     (custom-button-mouse-unraised ((t (:background "grey60" :foreground "black"))))
     (custom-button-mouse-pressed-unraised ((t (:background "grey60" :foreground "black"))))
     (custom-button-mouse ((t (:background "grey60" :foreground "black" :box (:line-width 1 :style released-button)))))
     (custom-button ((t (:background "grey50" :foreground "black" :box (:line-width 1 :style released-button)))))
     (cursor ((t (:background "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (completions-first-difference ((t (:bold t :weight bold :underline nil :underline nil :weight))))
     (completions-common-part ((t (:underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "#2e3436" :foreground "#eeeeec" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "DejaVu Sans Mono"))))
     (completions-annotations ((t (:italic t :slant italic :underline nil :underline nil :slant))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (comint-highlight-input ((t (:italic t :bold t :slant italic :weight bold))))
     (c-nonbreakable-space-face ((t (:bold t :background "#f57900" :weight bold))))
     (button ((t (:underline t))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (border ((t (:background "#888a85"))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bold ((t (:bold t :underline nil :weight bold))))
     (anything-header ((t (:bold t :background "grey15" :foreground "#edd400" :weight bold))))
     (ac-yasnippet-selection-face ((t (:background "coral3" :foreground "white"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     (ac-selection-face ((t (:background "blue" :foreground "white"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-etags-selection-face ((t (:background "deep sky blue" :foreground "white"))))
     (ac-etags-candidate-face ((t (:background "gainsboro" :foreground "deep sky blue"))))
     (ac-completion-face ((t (:background "darkblue" :foreground "white"))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (default ((t (:stipple nil :background "black" :foreground "NavajoWhite" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "DejaVu Sans Mono")))))))
(provide 'color-theme-luolE-blood-and-sand)