(defun color-theme-luolE-icecream ()
  "Color subtheme, created 2010-12-26."
  (interactive)
  (color-theme-install
   '(color-theme-luolE-icecream nil nil
     (yas/field-highlight-face ((t (:background "DarkSeaGreen1"))))
     (yas/field-debug-face ((t (nil))))
     (widget-single-line-field ((t (:background "royalblue"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-field ((t (:background "navy"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-button ((t (:bold t :weight bold))))
     (viper-search ((t (:background "khaki" :foreground "Black"))))
     (viper-replace-overlay ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-vi ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-minibuffer-insert ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-emacs ((t (:background "darkseagreen2" :foreground "Black"))))
     (vertical-border ((t (nil))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (underline ((t (:underline t))))
     (trailing-whitespace ((t (:background "red1"))))
     (tooltip ((t (:family "Sans Serif" :background "systeminfowindow" :foreground "systeminfotext"))))
     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
	 (tabbar-unselected-face ((t (:inherit tabbar-default-face))))
     (tabbar-separator-face ((t (:inherit tabbar-default-face))))
     (tabbar-selected-face ((t (:inherit tabbar-default-face :foreground "orangered"))))
     (tabbar-default-face ((t (:background "grey75" ))))
     (tabbar-button-face ((t (:inherit tabbar-default-face))))
     (speedbar-tag-face ((t (:foreground "white"))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (show-paren-match-face ((t (:background "grey80"))))
     (shadow ((t (:foreground "grey50"))))
     (secondary-selection ((t (:background "grey55"))))
     (scroll-bar ((t (:foreground "systemscrollbar"))))
     (region ((t (:background "grey80"))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (one-key-title ((t (:foreground "Gold"))))
     (one-key-prompt ((t (:foreground "khaki3"))))
     (one-key-keystroke ((t (:foreground "DarkRed"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (next-error ((t (:background "grey80"))))
     (mouse ((t (:background "grey15"))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line ((t (:background "grey50" :foreground "black" :box (:line-width -1 :style released-button)))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
     (match ((t (:background "yellow1"))))
     (linum ((t (:background "grey80" :foreground "grey20"))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (link ((t (:foreground "blue1" :underline t))))
     (lazy-highlight ((t (:background "yellow" :foreground "firebrick"))))
     (italic ((t (:underline t))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "VioletRed"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ibuffer-group-face ((t (:bold t :foreground "#F1266F" :weight bold :height 1.65))))
     (hl-paren-face ((t (:bold t :box (:line-width -1 :color "grey90" :style released-button) :weight bold))))
     (hl-line ((t (:background "LightSkyBlue"))))
     (highline-face ((t (:background "grey95"))))
     (highlight-symbol-face ((t (:background "gray90"))))
     (highlight ((t (:background "LightSkyBlue"))))
     (hi-yellow ((t (:background "yellow1"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-pink ((t (:background "pink"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-green ((t (:background "green1"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-blue ((t (:background "light blue"))))
     (hi-black-hb ((t (:bold t :family "Sans Serif" :weight bold :height 1.67))))
     (hi-black-b ((t (:bold t :weight bold))))
     (help-argument-name ((t (nil))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "black" :foreground "white" :box (:line-width 1 :style released-button)))))
     (fs-line-face ((t (:foreground "green" :underline nil :weight normal))))
     (fs-file-name-mouse-move-facese ((t (:bold t :background "red" :foreground "yellow" :weight bold))))
     (fs-file-name-face ((t (:bold t :foreground "red" :underline t :weight bold))))
     (fringe ((t (:background "grey90"))))
     (font-lock-warning-face ((t (:bold t :foreground "VioletRed" :weight bold))))
     (font-lock-variable-name-face ((t (:foreground "DarkGoldenrod"))))
     (font-lock-type-face ((t (:foreground "SteelBlue4"))))
     (font-lock-string-face ((t (:foreground "DarkRed"))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-preprocessor-face ((t (:foreground "ForestGreen"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-keyword-face ((t (:foreground "DarkBlue"))))
     (font-lock-function-name-face ((t (:foreground "SlateBlue"))))
     (font-lock-doc-face ((t (:foreground "DarkRed"))))
     (font-lock-constant-face ((t (:foreground "OliveDrab"))))
     (font-lock-comment-face ((t (:italic t :foreground "grey55" :slant italic))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "grey55"))))
     (font-lock-builtin-face ((t (:foreground "ForestGreen"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (escape-glyph ((t (:foreground "brown"))))
     (dropdown-list-selection-face ((t (:foreground "black" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "DejaVu Sans Mono" :background "purple" :height 98))))
     (dropdown-list-face ((t (:family "DejaVu Sans Mono" :foundry "outline" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 98))))
     (cursor ((t (:background "grey15"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (completions-common-part ((t (:family "DejaVu Sans Mono" :foundry "outline" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 98))))
     (completions-annotations ((t (:underline t))))
     (button ((t (:underline t))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (border ((t (nil))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bold ((t (:bold t :weight bold))))
     (ac-yasnippet-selection-face ((t (:background "coral3" :foreground "white"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     (ac-selection-face ((t (:background "steelblue" :foreground "white"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-etags-selection-face ((t (:background "deep sky blue" :foreground "white"))))
     (ac-etags-candidate-face ((t (:background "gainsboro" :foreground "deep sky blue"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "DejaVu Sans Mono")))))))
(provide 'color-theme-luolE-icecream)