(defun color-theme-luolE-element ()
  "Color subtheme, created 2010-04-18."
  (interactive)
  (color-theme-install
   '(color-theme-luolE-element nil nil
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yas/field-debug-face ((t (nil))))
     (widget-single-line-field ((t (:background "gray30" :foreground "orange"))))
     (widget-mouse-face ((t (:bold t :background "brown4" :foreground "white" :weight bold))))
     (widget-inactive ((t (:foreground "grey70"))))
	 (linum ((t (:background "gray10" :foreground "#666666"))))
     (widget-field ((t (:background "gray30" :foreground "orange"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-button ((t (:bold t :weight bold))))
     (vertical-border ((t (nil))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (underline ((t (:underline t))))
     (trailing-whitespace ((t (:background "red1"))))
     (tooltip ((t (:family "Sans Serif" :background "systeminfowindow" :foreground "systeminfotext"))))
     (tool-tips ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
     (tabbar-unselected-face ((t (:family "Cambria" :foreground "gray70" :background "gray30" :box (:line-width 2 :color "gray30") :height 0.8))))
     (tabbar-separator-face ((t (:family "Cambria" :foreground "gray70" :background "gray30" :height 0.16000000000000003))))
     (tabbar-selected-face ((t (:bold t :family "Cambria" :background "#A6E22A" :foreground "black" :box (:line-width 1 :color "#B0FF2A") :weight bold :height 0.8))))
     (tabbar-default-face ((t (:background "gray30" :foreground "gray70" :height 0.8 :family "Cambria"))))
     (tabbar-button-face ((t (:family "Cambria" :background "gray30" :foreground "dark red" :box (:line-width 1 :color "gray30") :height 0.8))))
     (show-paren-mismatch ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (show-paren-match ((t (:background "#73d216" :foreground "#2e3436"))))
     (shadow ((t (:foreground "grey70"))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (scroll-bar ((t (:foreground "systemscrollbar"))))
     (region ((t (:background "dark slate blue"))))
     (query-replace ((t (:foreground "#2e3436" :background "#f57900"))))
     (pulldown-default-selection-face ((t (:background "steelblue" :foreground "white"))))
     (pulldown-default-face ((t (:background "lightgray" :foreground "black" :underline "darkgray"))))
     (org-verse ((t (:italic t :foreground "#bbbbbc" :slant italic))))
     (org-verbatim ((t (:italic t :foreground "#eeeeec" :underline t :slant italic))))
     (org-todo ((t (:bold t :foreground "Red" :weight bold))))
     (org-special-keyword ((t (:foreground "brown"))))
     (org-quote ((t (:italic t :foreground "#bbbbbc" :slant italic))))
     (org-link ((t (:background "#2e3436" :foreground "skyblue2"))))
     (org-level-4 ((t (:bold t :foreground "tomato" :weight bold :height 1.0))))
     (org-level-3 ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
     (org-level-2 ((t (:bold t :foreground "#6ac214" :weight bold :height 1.2))))
     (org-level-1 ((t (:bold t :foreground "dodger blue" :weight bold :height 1.5))))
     (org-hide ((t (:foreground "#2e3436"))))
     (org-footnote ((t (:foreground "magenta3" :underline t))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-date ((t (:foreground "magenta3" :underline t))))
     (org-block ((t (:foreground "#bbbbbc"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (next-error ((t (:background "dark slate blue"))))
     (speedbar-tag-face ((t (:foreground "#A6E22A"))))
     (speedbar-separator-face ((t (:background "SteelBlue4" :foreground "white" :overline "gray"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-file-face ((t (:foreground "#89BDFF"))))
     (speedbar-directory-face ((t (:foreground "white"))))
     (speedbar-button-face ((t (:foreground "#F1266F"))))
     (mouse ((t (:background "#8ae234"))))
     (mode-line-inactive ((t (:background "#555753" :foreground "#bbbbbc"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-buffer-id ((t (:bold t :foreground "orange" :weight bold))))
     (mode-line ((t (:background "#222222" :foreground "#bbbbbc" :box (:line-width 1 :color nil :style released-button)))))
     (minibuffer-prompt ((t (:bold t :foreground "#729fcf" :weight bold))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-header-xheader-face ((t (:foreground "DeepSkyBlue1"))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-header-to ((t (:foreground "white"))))
     (message-header-subject ((t (:foreground "white"))))
     (message-header-other-face ((t (:foreground "VioletRed1"))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-name-face ((t (:foreground "green"))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-cc ((t (:foreground "white"))))
     (message-cited-text ((t (:foreground "#edd400"))))
     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
     (match ((t (:bold t :background "#e9b96e" :foreground "#2e3436" :weight bold))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (link ((t (:foreground "dodger blue" :underline t))))
     (lazy-highlight ((t (:background "#e9b96e" :foreground "#2e3436"))))
     (italic ((t (:italic t :underline nil :slant italic))))
     (isearch-fail ((t (:background "red4"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     (info-xref ((t (:foreground "#729fcf"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "#f57900"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (hl-line ((t (:background "brown4"))))
     (highlight ((t (:background "brown4"))))
     (help-argument-name ((t (nil))))
     (header-line ((t (:box (:line-width 1 :color nil :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (gnus-summary-selected ((t (:background "brown4" :foreground "white"))))
     (gnus-summary-normal-unread-face ((t (:foreground "white"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "indian red"))))
     (gnus-summary-normal-read-face ((t (:foreground "lime green"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "royal blue"))))
     (gnus-summary-low-unread-face ((t (:italic t :foreground "white" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "dark red" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "royal blue" :slant italic))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "lime green" :slant italic))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "white" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "tomato" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "lime green" :weight bold))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "rotal blue" :weight bold))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-signature-face ((t (:italic t :foreground "dark grey" :slant italic))))
     (gnus-header-subject ((t (:foreground "#edd400"))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3" :slant italic :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "#729fcf" :weight bold))))
     (gnus-header-from ((t (:bold t :foreground "#edd400" :weight bold))))
     (gnus-header-content ((t (:italic t :foreground "#8ae234" :slant italic))))
     (gnus-group-news-low-face ((t (:bold t :foreground "dodger blue" :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "#edd400" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "#729fcf"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "dodger blue" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "#edd400" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "#729fcf"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-mail-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-cite-face-4 ((t (:foreground "PaleTurquoise4"))))
     (gnus-cite-face-3 ((t (:foreground "khaki4"))))
     (gnus-cite-face-2 ((t (:foreground "sienna4"))))
     (gnus-cite-face-1 ((t (:foreground "#ad7fa8"))))
     (fs-line-face ((t (:foreground "green" :underline nil :weight normal))))
     (fs-file-name-face ((t (:bold t :foreground "red" :underline t :weight bold))))
     (fringe ((t (:background "grey10"))))
     (font-lock-warning-face ((t (:bold t :foreground "#f57900" :weight bold))))
     (font-lock-variable-name-face ((t (:foreground "tomato"))))
     (font-lock-type-face ((t (:bold t :foreground "#8ae234" :weight bold))))
     (font-lock-string-face ((t (:italic t :foreground "#ad7fa8" :slant italic))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold :underline nil))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :underline nil))))
     (font-lock-preprocessor-face ((t (:foreground "#729fcf"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-keyword-face ((t (:bold t :foreground "#729fcf" :weight bold))))
     (font-lock-function-name-face ((t (:bold t :foreground "#edd400" :weight bold))))
     (font-lock-doc-face ((t (:foreground "#888a85"))))
     (font-lock-constant-face ((t (:foreground "#8ae234"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#888a85"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (expander-face ((t (:background "darkblue" :foreground "white"))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "White" :weight bold))))
     (eshell-ls-special-face ((t (:bold t :foreground "Gold" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "black" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "Coral" :weight bold))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "DimGray" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (epa-validity-medium ((t (:italic t :foreground "PaleTurquoise" :slant italic))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-string ((t (:foreground "lightyellow"))))
     (epa-mark ((t (:bold t :foreground "orange" :weight bold))))
     (epa-field-name ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-field-body ((t (:italic t :foreground "turquoise" :slant italic))))
     (dropdown-list-selection-face ((t (:foreground "black" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "DejaVu Sans Mono" :background "purple" :height 98))))
     (dropdown-list-face ((t (:family "DejaVu Sans Mono" :foundry "outline" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 98))))
     (diary-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
     (custom-variable-button ((t (:box (:line-width 1 :style released-button) :foreground "black" :background "grey50"))))
     (custom-state-face ((t (:foreground "#729fcf"))))
     (custom-link ((t (:underline t :foreground "dodger blue"))))
     (custom-group-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.3))))
     (custom-face-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
     (custom-documentation ((t (:italic t :slant italic))))
     (custom-button-unraised ((t (:background "grey50" :foreground "black"))))
     (custom-button-pressed ((t (:foreground "black" :background "grey50" :box (:style pressed-button)))))
     (custom-button-mouse-unraised ((t (:foreground "black" :background "grey60"))))
     (custom-button-mouse-pressed-unraised ((t (:foreground "black" :background "grey60"))))
     (custom-button-mouse ((t (:box (:line-width 1 :style released-button) :foreground "black" :background "grey60"))))
     (custom-button ((t (:background "grey50" :foreground "black" :box (:line-width 1 :style released-button)))))
     (cursor ((t (:background "#fce94f"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (completions-first-difference ((t (:bold t :weight bold :underline nil))))
     (completions-common-part ((t (:family "DejaVu Sans Mono" :foundry "outline" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeec" :background "#2e3436" :stipple nil :height 98))))
     (completions-annotations ((t (:italic t :slant italic :underline nil))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (comint-highlight-input ((t (:italic t :bold t :slant italic :weight bold))))
     (button ((t (:underline t))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (border ((t (:background "#888a85"))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bold ((t (:bold t :underline nil :weight bold))))
     (anything-header ((t (:bold t :background "grey15" :foreground "#edd400" :weight bold))))
     (ac-yasnippet-selection-face ((t (:background "coral3" :foreground "white"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     (ac-selection-face ((t (:background "blue" :foreground "white"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-etags-selection-face ((t (:background "deep sky blue" :foreground "white"))))
     (ac-etags-candidate-face ((t (:background "gainsboro" :foreground "deep sky blue"))))
     (ac-completion-face ((t (:background "darkblue" :foreground "white"))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (default ((t (:stipple nil :background "#2e3436" :foreground "#eeeeec" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "DejaVu Sans Mono")))))))
(provide 'color-theme-luolE-element)